# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: code_executor.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'code_executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ode_executor.proto\x12\rcode_executor\"$\n\x14\x43odeExecutionRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"I\n\x15\x43odeExecutionResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x11\n\texit_code\x18\x03 \x01(\x05\x32j\n\x0c\x43odeExecutor\x12Z\n\x0b\x45xecuteCode\x12#.code_executor.CodeExecutionRequest\x1a$.code_executor.CodeExecutionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'code_executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODEEXECUTIONREQUEST']._serialized_start=38
  _globals['_CODEEXECUTIONREQUEST']._serialized_end=74
  _globals['_CODEEXECUTIONRESPONSE']._serialized_start=76
  _globals['_CODEEXECUTIONRESPONSE']._serialized_end=149
  _globals['_CODEEXECUTOR']._serialized_start=151
  _globals['_CODEEXECUTOR']._serialized_end=257
# @@protoc_insertion_point(module_scope)
